### ISSUE TITLE
✨ Feature request: Leverage ansible-tox within pipeline

### ISSUE THREAD

**Issue by nwerker** [svalabs/sva.sentinelone#17]
##### SUMMARY
At the moment the test matrix which ansible-core and python version should the CI test against is manually maintained. This could be maybe automated by utilising the [tox-ansible](https://github.com/tox-dev/tox-ansible) project.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
[.github/workflows/ansible-test.yml](https://github.com/svalabs/sva.sentinelone/blob/main/.github/workflows/ansible-test.yml)

##### ADDITIONAL INFORMATION
tox-ansible has a github matrix which includes all the current Versions to test against.

This matrix can be listed via the cli like this:

```bash
tox --ansible --gh-matrix
```

Output (extract):
```json
[
  {
    "description": "Integration tests using ansible 2.9 and python 3.7",
    "factors": [
      "integration",
      "py3.7",
      "2.9"
    ],
    "name": "integration-py3.7-2.9",
    "python": "3.7"
  },
  {
    "description": "Integration tests using ansible 2.9 and python 3.8",
    "factors": [
      "integration",
      "py3.8",
      "2.9"
    ],
    "name": "integration-py3.8-2.9",
    "python": "3.8"
  },
  {
    "description": "Integration tests using ansible-core 2.12 and python 3.8",
    "factors": [
      "integration",
      "py3.8",
      "2.12"
    ],
    "name": "integration-py3.8-2.12",
    "python": "3.8"
  },
...
]
```

**Comment by nwerker** [comment]
There is a new project that could potentially replace our pipelines we use at the moment: https://github.com/ansible/ansible-content-actions

**Comment by mwester117** [comment]
Won't fix. is obsoleted by https://github.com/svalabs/sva.sentinelone/issues/34
